version: "3"
services:
  rank0:
    build: .
    networks:
      dist-bridge:
        ipv4_address: 10.1.0.10
    command: python -u main.py --init-method tcp://10.1.0.10:23456 --rank 0 --world-size 2
  rank1:
    build: .
    networks:
      dist-bridge:
        ipv4_address: 10.1.0.11
    command: python -u main.py --init-method tcp://10.1.0.10:23456 --rank 1 --world-size 2
networks:
  dist-bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
